trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python27Linux:
        imageName: 'ubuntu-16.04'
        python.version: '2.7'
      Python27Mac:
        imageName: 'macos-10.14'
        python.version: '2.7'
      Python35Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.5'
      Python35Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.5'
      Python35Mac:
        imageName: 'macos-10.14'
        python.version: '3.5'
      Python36Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      Python36Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.14'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
      Python37Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-10.14'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.8'
      Python38Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-10.14'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.9'
      Python39Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-10.14'
        python.version: '3.9'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip wheel
    displayName: 'Install dependencies'

  - script: |
      python setup.py build_ext --inplace
      python setup.py sdist
    displayName: 'Build sdist'

  - script: pip install dist/*.tar.gz
    condition: in( variables['Agent.OS'], 'Linux', 'Darwin')
    displayName: 'Install from sdist (Linux, Mac)'

  - script: pip install -e .
    condition: eq( variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install with pip (Windows)'

  - script: |
      pip install -r requirements.txt
      python -m pytest preshed
    displayName: 'Run tests'
